# Imports

In [1]:
import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# Read the Data

In [2]:
df = pd.read_csv('Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
X = df.drop(columns=['Id', 'Species'])
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [7]:
y = df.Species.str.strip().eq('Iris-setosa').astype(int)
y

0      1
1      1
2      1
3      1
4      1
      ..
145    0
146    0
147    0
148    0
149    0
Name: Species, Length: 150, dtype: int64

# Split the Data

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state= 2026)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(120, 4) (120,)
(30, 4) (30,)

In [23]:
y_train.value_counts(normalize=True)

Species
0    0.666667
1    0.333333
Name: proportion, dtype: float64

In [24]:
y_test.value_counts(normalize=True)

Species
0    0.666667
1    0.333333
Name: proportion, dtype: float64

# Train the Model

In [15]:
model = LogisticRegression().fit(X_train.values, y_train.values)
model

LogisticRegression()

# Model Evaluation

In [16]:
y_train_pred = model.predict(X_train.values)
y_test_pred = model.predict(X_test.values)

print(f'Train Acc: {accuracy_score(y_train, y_train_pred)}')
print(f'Test Acc: {accuracy_score(y_test, y_test_pred)}')

Train Acc: 1.0
Test Acc: 1.0

# Model Output Format

In [17]:
y_train_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1])

In [18]:
X_train.values[0]

array([6.2, 2.2, 4.5, 1.5])

In [19]:
model.predict(np.array([[6. , 2.7, 5.1, 1.6]]))

array([0])

# Serialization

In [22]:
joblib.dump(model, 'model.joblib')

['model.joblib']